[versions]
kotlin = "1.8.21"
coroutine = "1.7.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
agp-app = { id = "com.android.application", version = "8.2.2" }
lsplugin-resopt = { id = "org.lsposed.lsplugin.resopt", version = "1.5" }
lsplugin-cmaker = { id = "org.lsposed.lsplugin.cmaker", version = "1.1" }

[libraries]
xposed = { module = "de.robv.android.xposed:api", version = "82" }
cxx = { module = "dev.rikka.ndk.thirdparty:cxx", version = "1.2.0" }
dexmaker = { module = "com.linkedin.dexmaker:dexmaker", version = "2.28.3" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
kotlin-coroutines-jdk = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutine" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.7.1" }
